### ISSUE TITLE
Update for Things3

### ISSUE THREAD

**Issue by fintelkai** [mailmate/things.mmbundle#1]
Now that Things3 is out, the applescript incantation needs to say `tell application "Things3"`

**Comment by freron** [comment]
Have you tested this change?

I cannot see that Things3 has been released (on the homepage) and therefore I cannot test it. In order for it to work with the old version of Things as well then something like this is needed in the script:

~~~
	try
		tell application "Finder" to get application file id "com.culturedcode.Things3Mac"
		tell application "Things3"
			show quick entry panel with properties {name:theName, notes:theMessage & "\n" & theNote}
		end tell
	on error
		tell application "Things"
			show quick entry panel with properties {name:theName, notes:theMessage & "\n" & theNote}
		end tell
	end try
~~~

Note that I've only tried to guess the bundle id for Things3. You can look it up here:

    Things3.app/Contents/Info.plist

**Comment by fintelkai** [comment]
"Have you tested this change?" Yes, it works with Things 3 (a free trial of which is available at the Cultured Code website (https://culturedcode.com/things/download/). I don't have the old version so I can't test the conditional. 

Looking at the Info.plist of the new version, I see 

```	
<key>CFBundleIdentifier</key>
<string>com.culturedcode.ThingsMac</string>
```

and

```
<key>CFBundleName</key>
<string>Things3</string>
```

I attach the Info.plist (had to change the extension to make github allow this).

[Info.plist.txt](https://github.com/mailmate/things.mmbundle/files/1014000/Info.plist.txt)

**Comment by freron** [comment]
In that case I think the bundle identifier hasn't changed. Try changing the line to simply state:

    tell application id "com.culturedcode.ThingsMac"

Does that work?

**Comment by freron** [comment]
I went ahead and made the change since I could see it worked with the previous version of Things. I haven't checked with Things3, but based on your information I would be surprised if it's not the same.

(Caveat: They might have changed how the AppleScript interface works.)

**Comment by freron** [comment]
MailMate should auto-update the bundle within a few hours, but you can also disable and then re-enable the bundle in the preferences pane to trigger an update.

**Comment by freron** [comment]
Hmm, it's not really called Things3. I think it might be a bug they have it in the `Info.plist` file.

In any case, I believe the issue has been resolved.

**Comment by fintelkai** [comment]
Yes, that works.
